### ISSUE TITLE
Support VIRL_VERIFY_CERT=False in .virlrc as well as ENV

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/virlutils#100]
Currently the ability to disable SSL verification, or providing a SSL bundle are only supported as ENV.  Would be good to add these as configurable in .virlrc.  

Potentially look at adding to the `VIRLServer.config` properties and `get_credentials` along with other properties. 

https://github.com/CiscoDevNet/virlutils/blob/cml2-dev/virl/api/credentials.py#L115

**Comment by xorrkaz** [comment]
This is fixed now.
