### ISSUE TITLE
Getting `unsupported operand type(s) for +: 'NoneType' and 'str'` on virl up

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/virlutils#101]
**Describe the bug**
Initial testing of `virl up` on CML2 and getting error: 

```
unsupported operand type(s) for +: 'NoneType' and 'str'
```

I do get a simulation started from the command, and `virl nodes` shows the nodes.  But additional `virl up` starts multiple simulations. 

Still digging into the problem to figure out where the issue lies.

**Comment by hpreston** [comment]
Current .virlrc file contents (minus the host/user info)

```
VIRL_HOST=******** 
VIRL_USERNAME=******** 
VIRL_PASSWORD=********
VIRL_VERIFY_CERT=False
CML2_PLUS="yes"

VIRL_TELNET_COMMAND="telnet {host}"
VIRL_CONSOLE_COMMAND="telnet {host}"
VIRL_SSH_COMMAND="ssh {host}"

VIRL_SSH_USERNAME="cisco"
VIRL_SSH_PASSWORD="cisco"

CML_CONSOLE_COMMAND="telnet {host}"
```

Running against the Sandbox pod server and the attached lab file.

[lab1.yaml.txt](https://github.com/CiscoDevNet/virlutils/files/4604846/lab1.yaml.txt)

**Comment by xorrkaz** [comment]
I cannot reproduce this with the latest pull from cml2-dev.  That said, I didn't do anything to fix it.  Is this reliably reproducible for you?

**Comment by xorrkaz** [comment]
This is fixed now.  The previous code died if a `.virl` directory didn't yet exist anywhere in the directory tree.
