### ISSUE TITLE
unable to find .virlrc on windows 10

### ISSUE THREAD

**Issue by cischology** [CiscoDevNet/virlutils#103]
running virlutils on Windows 10 and every time I try to ls or virl up I am being asked to provide server ip plus user/password. I couldn't find and documentation that shows how to replicate .virlrc content on a windows environment. 

Thank you for the hard work you do.

**Comment by xorrkaz** [comment]
The simplest place to put your .virlrc file is in the same directory where you run `virl`.  At its simplest, it would look like:

```
VIRL_HOST=192.168.10.214
VIRL_USERNAME=guest
VIRL_PASSWORD=guest
```

**Comment by cischology** [comment]
> The simplest place to put your .virlrc file is in the same directory where you run `virl`. At its simplest, it would look like:
> 
> ```
> VIRL_HOST=192.168.10.214
> VIRL_USERNAME=guest
> VIRL_PASSWORD=guest
> ```

Thank you for your reply. I understand what you mean however, i am not sure if Windows will allow me to name a file .virlrc (due to windows file naming convention). i will go try it right after this post and keep you updated.

**Comment by cischology** [comment]
as i anticipated Windows will not allow you to have a file name that starts with "."
![image](https://user-images.githubusercontent.com/56488147/84577776-22cea100-ad74-11ea-9ca1-6f5a5f919d07.png)

**Comment by cischology** [comment]
adding virlrc file with the content did not solve my issue , I am still being asked to provide server ip and username/password
VIRL_HOST=<my virl server ip>
VIRL_USERNAME=guest
VIRL_PASSWORD=guest

**Comment by xorrkaz** [comment]
The file must be `.virlrc`, even on Windows.  The likely intent was that Windows users would be using a more CLI-driven workflow like Git Bash or Powershell, where I think you can create a file called .virlrc (e.g., in vim from within Git Bash).

That said, you can simple set these same variables in your environment (e.g., `set VIRL_HOST = ...`) and that will work.

Something else, we're removing support for Python 2 in the next release of virlutils (which will also have CML 2 support).  You should consider upgrading your Python to 3.x (3.7 or higher for best results).

**Comment by cischology** [comment]
regardless of Python 2 or 3 ... I think the file structure should me the same and i will still face the same issue I am facing now. In Windows, how do I substitute for the .virlrc file :)

p.s I am testing different folder path and will post in if I figure out a solution.

**Comment by xorrkaz** [comment]
See above where I mentioned how to create the file using one of the alternate windows shell options or to use the environment to store your parameters.

**Comment by xorrkaz** [comment]
Have you been able to create the `.virlrc` file using powershell or bash?

**Comment by cischology** [comment]
> Have you been able to create the `.virlrc` file using powershell or bash?

Yes. Thank you so much you can close this as resolved.
