### ISSUE TITLE
CML Tab Completion

### ISSUE THREAD

**Issue by usmcfiredog** [CiscoDevNet/virlutils#104]
**Is your feature request related to a problem? Please describe.**
I have downloaded and testing the cml2-dev branch and noticed that tab completion does not work when using the cml command. It does work if I use the virl commands.

**Describe the solution you'd like**
Tab completions when using the cml command set

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by xorrkaz** [comment]
Should work now.  Well, it always did, but you needed an additional command.  Pull the latest from this branch and look at the new docs.

**Comment by usmcfiredog** [comment]
sorry for the delay but the tab completion for cml does not work still. I am using zsh for my shell and have the commands loaded for it. The tab completion for the VIRL commands work but not for cml

**Comment by xorrkaz** [comment]
I also use zsh and tab completion works for me after I've done:

```sh
autoload bashcompinit
bashcompinit

eval "$(_CML_COMPLETE=source cml)"
```

**Comment by usmcfiredog** [comment]
that last command was needed... thank you for the quick reply and work... keep up the great work!

**Comment by usmcfiredog** [comment]
also do you know why I get the following messages when I run the eval command:
_cml_completionetup:[:4: unknown condition: -gt
_cml_completionetup:[:4: unknown condition: -eq

I get the same when I run the virl_complete one also.

**Comment by xorrkaz** [comment]
It's a zsh thing.  If you use:

eval "$(_CML_COMPLETE=source_zsh cml)"

You won't get the warnings.

**Comment by usmcfiredog** [comment]
thank you
