### ISSUE TITLE
Parallel execution of extracting node config in cml save command

### ISSUE THREAD

**Issue by radiantmarch** [CiscoDevNet/virlutils#108]
**Is your feature request related to a problem? Please describe.**
Every time I use virlutils `cml save` command, it tries to extract config from node one by one. It may take long time when I have lot of nodes. 

**Describe the solution you'd like**
Run process of extracting configs from nodes in parallel.

**Describe alternatives you've considered**
None.

**Additional context**
Reducing time to save topology/config will benefit users. Also the time required to save/extract configs from node affects use of CML in CI/CD process.

**Comment by xorrkaz** [comment]
I have implemented concurrency in my dev branch.  Testing shows this gives a 160% performance improvement with smaller topologies.  I would expect a substantially larger time savings in larger topologies.  This will be part of the 1.2.0 release due out after CML 2.1 comes out.

**Comment by xorrkaz** [comment]
This has been fixed in virlutils 1.2.0.
