### ISSUE TITLE
Failed to license simulation

### ISSUE THREAD

**Issue by markheinemann** [CiscoDevNet/virlutils#110]
Hello, 
working in Ubuntu WSL  distro on windows 10

i am connected via vpn to sandbox: open nx-os with Nexus 9kv

after entering command

(venv) mark@mark-Zoo:~$ virl up virlfiles/5_router_mesh

i encounter this error:

Exception raised while running your command
Please re-run as 'virl --debug ...' and collect the output before opening an issue
403 Client Error: Failed to license simulation. for url: http://10.10.20.160:19399/simengine/rest/launch?session=mark_default_a0WgJU

any assistance is appreciated

**Comment by xorrkaz** [comment]
This is not a virlutils issue.  You need to first stop the topology running on the CML instance in Sandbox to free up enough licenses to run your new topology.

If you're looking for a general CML to use, I recommend you reserve the CML 2.0 Enterprise Sandbox.
