### ISSUE TITLE
License is marked as UNKNOWN in the PKG-INFO

### ISSUE THREAD

**Issue by ttafsir** [CiscoDevNet/virlutils#111]
**Describe the bug**
The license is as marked as UNKNOWN making it unusable in our environment.

**To Reproduce**

→ 09:09:10$ in ~/Projects/virlutils  on master [!]$ pip-licenses
virlutils          1.2.1       UNKNOWN 

**Expected behavior**
expected MIT License as it is in the repository

**Comment by xorrkaz** [comment]
This has been fixed in 1.2.2, but turns out while your PR worked for building, it did not work for release to PyPi.  Therefore, I went with another approach.
