### ISSUE TITLE
update/remove README_virl1.md

### ISSUE THREAD

**Issue by eckelcu** [CiscoDevNet/virlutils#113]
README_virl1.md appears to have been an attempt to maintain a README for VIRL 1.x specific functionality while updating the main README for CML 2.0 with backward compatibility for VIRL 1.x when possible. However, in its current form, README_virl1.md seems duplicative and slightly out of date with README.md, including referencing itself as the reference for complete compatibility with VIRL 1.x. 

I suggest either,
1) update README_virl1.md to really be specfic to VIRL 1.x
2) remove README_virl1.md and the reference to it in README.md

My preference is for the latter. I am happy to send a PR if helpful.

**Comment by xorrkaz** [comment]
I reverted the README_virl1 text and added a note at the top.
