### ISSUE TITLE
Request for advice/help on SSLCertVerificationError errors when using cmlutils.

### ISSUE THREAD

**Issue by gerardgillan** [CiscoDevNet/virlutils#117]
Hi,

My employer has recently upgraded to CML2 and I came across virlutils/cmlutils when searching for a method to allow us to directly connect to a lab/node using ssh from a workstation. The utils look great and we're really excited to try them out.

```
c:\>cml version
virlutils Version: 1.3.1
CML Controller Version: 2.1.1-b19
```
We have followed the set-up instructions including creating a .virlrc file containing CML server, username & password details and a CML_VERIFY_CERT=False entry. While we receive a successful response to the "cml ls" command we are receive (see attached output.txt) _SSLCertVerificationError_ errors when trying to run "cml search" or "up" a lab. We can successfully get to https://api.github.com/orgs/virlfiles/repos via a browser and a postman get call.

[output.txt](https://github.com/CiscoDevNet/virlutils/files/6131278/output.txt)

Are you aware if anyone has encountered similar issues and if so how they were able to resolve them? 

Previously when experiencing similar _SSLCertVerificationError_ errors (e.g. when trying to use pip install) we have been able to get around this using a _--trusted-host_ entry but have not been able to work out how we could use this with cmlutils.

Any advice or help would be greatly appreciated.

**Comment by xorrkaz** [comment]
Interesting.  I don't see this, and I wonder if you have some middlebox doing the decryption for you.  Have a look at https://github.com/box/box-python-sdk/issues/438 and see if getting that cert and setting the REQUESTS_CA_BUNDLE envvar helps.

**Comment by gerardgillan** [comment]
Thanks xorrkaz/Joe,
We have set my REQUESTS_CA_BUNDLE envvar as per _box/box-python-sdk#438_ and can now successfully execute the "cml search" command however we now receive an error regarding self signed certificate from our onsite CML2 server when we run "cml ls".  We have set CML_VERIFY_CERT=False in my local .virlrc file.
```
c:\>cml ls
Exception raised while running your command
Please re-run as 'cml --debug ...' and collect the output before opening an issue
HTTPSConnectionPool(host='cml20.lab.local', port=443): Max retries exceeded with url: /api/v0/system_information (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)')))
```

**Comment by xorrkaz** [comment]
I'm not sure how what you're seeing is possible.  Are you sure you're still running `cml` from the directory with your `.virlrc`? I've tried to reproduce this locally, and I cannot.  One obvious workaround would be to add your CML self-signed cert to that same bundle location, but still, I don't know why you're seeing this.  From a code flow perspective, this shouldn't happen if `CML_VERIFY_CERT=False` is set.

**Comment by gerardgillan** [comment]
Thanks xorrkaz/Joe,
Apologies for not responding sooner. I've taken some FTO this week but will be back at work on Monday, will retry connecting and will get back with an update.

**Comment by gerardgillan** [comment]
Hi xorrkaz/Joe,

I have attached a screen shot of the output that I am receiving. I created the .virlrc file (with CML_VERIFY_CERT=False) in a directory I have called virlutils and am running the "_cml search_" and "_cml ls_" commands within that directory. 

- I checked the REQUESTS_CA_BUNDLE value prior to running any of the cmlutil commands and confirmed that it was blank
- I can successfully run the "_cml ls_" command but receive the SSL error when trying to run the "_cml search_" command.
- I configureed the REQUESTS_CA_BUNDLE as per box/box-python-sdk#438 with the location of my cacert.pem file
- I can then successfully run the "_cml search_" command but receive the SSL error when trying to run the "_cml ls_" command.
- I remove the the location of my cacert.pem file from the configuration of REQUESTS_CA_BUNDLE
- I can again successfully run the "_cml ls_" command but receive the SSL error when trying to run the "_cml search_" command.

![Screenshot of cmlutils errors 2021-03-22](https://user-images.githubusercontent.com/28629848/111999243-b5c31580-8b14-11eb-8c48-2769f1c92984.png)

**Comment by xorrkaz** [comment]
I see the problem now.  It's requests itself that is refusing to work with the certificate, and the ssl_verify is not passed to each request() call via the Python Client Library.

So in order for you to work properly, you need to add your CML server's cert to your REQUESTS_CA_BUNDLE file.  Then both search and ls should work for you.

**Comment by gerardgillan** [comment]
Hi xorrkaz/Joe,

Thank you, I'll do that. I appreciate all your help!

**Comment by gerardgillan** [comment]
need to add CML server's cert to your REQUESTS_CA_BUNDLE file
