### ISSUE TITLE
Tab Completions

### ISSUE THREAD

**Issue by usmcfiredog** [CiscoDevNet/virlutils#123]
**Describe the bug**
After following all instructions on the readme I am unable to get tab completions to work.

**To Reproduce**
clean install of macOS with pyenv and pyenv-virtualenv unable to get tab completion to work.

**Expected behavior**
type cml l<tab> and have it list ls and license

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 11.4
 - Browser Safari
 - Version 14.1.1
 - Python version 3.8.9
 - Pyenv 2.0.0
 - Pyenv-virtualenv 1.1.5

**Additional context**
able to work on another Mac that has had it working previously, before upgrading to the same versions as above. Only difference is that the other Mac is on the cml-dev branch where this issue is on the master branch

**Comment by xorrkaz** [comment]
I have fixed the instructions in the README based on the latest `click` documentation.  I tested:

```sh
cml l<tab><tab>
license  -- work with product licensing
ls       -- lists running labs and optionally those in...
```

**Comment by usmcfiredog** [comment]
thank you works perfectly
