### ISSUE TITLE
cml pull will not pull sample labs anymore

### ISSUE THREAD

**Issue by usmcfiredog** [CiscoDevNet/virlutils#124]
**Describe the bug**
when attempting to pull sample labs I get an error.
cml pull ccnx_study or cml pull virlfiles/ccnx_study
I get 
Pulling from ccnx_study
Error pulling ccnx_study - repo not found
or
Pulling from virlfiles/ccnx_study
Error pulling virlfiles/ccnx_study - repo not found

**To Reproduce**
1. cml search
2. cml pull <any lab from previous>

**Expected behavior**
Download topofile from GitHub 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.4

**Additional context**

**Comment by xorrkaz** [comment]
This is fixed in my development branch.

**Comment by usmcfiredog** [comment]
do you know when it will be pushed to the master and have the packages updated?

**Comment by xorrkaz** [comment]
This is now fixed in 1.3.4.  Thanks for reporting.
