### ISSUE TITLE
Problem with console command

### ISSUE THREAD

**Issue by VitMain** [CiscoDevNet/virlutils#135]
virl version
virlutils Version: 1.3.7
CML Controller Version: 2.3.1+build29

virl console cat8000v-0
admin@controller's password:
console "/aeb0c0ae-3f57-45e4-a036-7ddaf5cda030/2bc22557-a8cd-4e3f-b600-7960589880c5/0" not found!
Connection to controller closed.

**Comment by xorrkaz** [comment]
Looks like a valid bug.  CML 2.3 changed the way the console server works so that only names work for lab and node.

**Comment by xorrkaz** [comment]
This has been fixed in 1.3.8.  Thanks for reporting.

**Comment by VitMain** [comment]
Thank you!
