### ISSUE TITLE
cml tmux broken

### ISSUE THREAD

**Issue by sgherdao** [CiscoDevNet/virlutils#148]
Hi @xorrkaz 

Looks like after a change in libtmux, `cml tmux` is broken (tmux-python/libtmux#533).

Could we pin libtmux to 0.27 for now, ideally on master? Let me know if you want me to submit a PR.

Thanks,

**Comment by sgherdao** [comment]
Hi @tony,

Tested 0.34 and it looks good, thank you for expediting this!

Joe, we can either leave it like this or exclude libtmux versions > 0.27.0, < 0.34.0.


Thanks all,

Salah

**Comment by xorrkaz** [comment]
It was easier to just go with 0.34 and later.  I did this and pushed a 2.0.1 release.
