### ISSUE TITLE
Need to account for options which may not be configured on the VIRL server

### ISSUE THREAD

**Issue by automanetwork** [CiscoDevNet/virlutils#42]
Localization allows for tags in VIRL XML to be replaced with configuration from the VIRL server, need to handle cases where those options may not be configured on the server. 

https://github.com/kecorbin/virlutils/blob/master/virl/cli/up/commands.py#L39

Specifically, DNS servers are often not configured for the shared networks. 
https://github.com/kecorbin/virlutils/blob/master/virl/api/api.py#L186
can lead to the following error message
```
Exception raised while running your command
Please open an issue and provide this info:
list index out of range
```

**Comment by securenetwrk** [comment]
I can confirm, I was getting the same error and adding DNS resolved it. I would suggest at a minimum adding a check for empty DNS list and telling people to add DNS entries since the error did not indicate the root cause.

**Comment by dcrearer** [comment]
I'm getting the following error when using the virl up command 

(venv) 22:07:33> virl up  virlfiles/2-ios-router
Pulling from virlfiles/2-ios-router
Saved topology as topology.virl
Creating default environment from topology.virl
Exception raised while running your command
Please open an issue and provide this info:
list index out of range

**Comment by kecorbin** [comment]
@dcrearer can you provide the virl version you are using?  we did have a bad build that snuck out to pypi.  0.8.8 should be stable
