### ISSUE TITLE
Generation of Ansible Inventory takes a long time

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/virlutils#53]
**Describe the bug**
Running `virl generate ansible` can take a very long time to complete.  

**To Reproduce**
1. Run `virl generate ansible`
2. Time how long it takes

**Expected behavior**
Would expect it to finish in <1min

**Comment by kecorbin** [comment]
I've observed this as well in some situations.  It seems to be somehow related to the topology itself.

**Comment by xorrkaz** [comment]
This is believed to have been fixed in the latest virlutils when using CML 2 support.
