### ISSUE TITLE
Output of virl up --provision is misleading

### ISSUE THREAD

**Issue by kecorbin** [CiscoDevNet/virlutils#54]
**Is your feature request related to a problem? Please describe.**
virl up --provision provides the following message to users:

`Waiting 10 minutes for nodes to come online....`

This is a bit misleading, as it will likely finish sooner (10 minutes is the default timeout)

**Describe the solution you'd like**

Make it better
**Describe alternatives you've considered**

`Waiting up to 10 minutes for nodes to come online`

**Additional context**

**Comment by xorrkaz** [comment]
This is no longer a factor for CML 2 support.
