### ISSUE TITLE
Add the ability to add images to VIRL server via CLI

### ISSUE THREAD

**Issue by kecorbin** [CiscoDevNet/virlutils#60]
**Is your feature request related to a problem? Please describe.**

Assuming that you have a qcow or other image, be able to upload it to the VIRL server, and register appropriate subtypes

**Describe the solution you'd like**

Extra credit would be to detect what subtypes are required for a given simulation, and load them dynamically if not already present.

**Comment by xorrkaz** [comment]
This has been implemented for CML 2.
