### ISSUE TITLE
Support for VIRL Flavors

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/virlutils#61]
**Is your feature request related to a problem? Please describe.**
No.  Requesting this feature to help provide scriptable configuration of VIRL in sandboxes.

**Describe the solution you'd like**
Support for VIRL Flavors.  This support should include the ability to:
- Create a Flavor
- List Flavors (Summary and Detail)
- Modify Flavors
- Remove Flavors

Note: The VIRL management web portal (I don't think) permits modification of flavors so the Modify/Update feature may not be possible.  

**Describe alternatives you've considered**
-NA-

**Additional context**

**Comment by kecorbin** [comment]
I’ve started looking into this.  It appears that modifications are not possible.  Deleting and recreating is however so same effect I guess.  This is also closely related to #60

**Comment by gve-vse-tim** [comment]
Hey Kevin,

I actually took a crack at the code and have most of it done.  Need to do the unit testing parts and I’ll be all finished.

Let me know and when I get finished this week I’ll send a pull request.

Tim

Sent from my iPhone

On Sep 2, 2018, at 08:49, Kevin Corbin <notifications@github.com<mailto:notifications@github.com>> wrote:


I’ve started looking into this. It appears that modifications are not possible. Deleting and recreating is however so same effect I guess. This is also closely related to #60<https://github.com/CiscoDevNet/virlutils/issues/60>

**Comment by kecorbin** [comment]
@gve-vse-tim i believe can be closed now - can you confirm?

**Comment by gve-vse-tim** [comment]
Confirmed!

Sent from my iPhone

On Apr 4, 2019, at 14:10, Kevin Corbin <notifications@github.com<mailto:notifications@github.com>> wrote:


@gve-vse-tim<https://github.com/gve-vse-tim> i believe can be closed now - can you confirm?
