### ISSUE TITLE
`virl uwm` and `virl viz` do not work on windows

### ISSUE THREAD

**Issue by kecorbin** [CiscoDevNet/virlutils#65]
**Describe the bug**
These commands rely on the presence of a launcher executable such as `open` on MacOS
which does not exist on Windows (or linux??) 

something like:
```
start filename_or_URL
```

should be equivalent on Windows (https://www.dwheeler.com/essays/open-files-urls.html)

**To Reproduce**

From windows attempt `virl uwm`

**Expected behavior**

A browser session to the appropriate UWM page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser likely doesnt matter

**Additional context**

**Comment by xorrkaz** [comment]
This is likely the same in CML 2 land with `cockpit` and `ui`.

**Comment by xorrkaz** [comment]
VIRL 1.x support has been EOL'd.  Without any confirmation of "cockpit" and "ui", I am closing this issue.  Re-open if the problem persists with these commands in cmlutils.
