### ISSUE TITLE
`virl generate pyats` should generate all connection times

### ISSUE THREAD

**Issue by kecorbin** [CiscoDevNet/virlutils#68]
**Is your feature request related to a problem? Please describe.**
Currently, only console information is generated for devices, if flat networking is configured, we can also get the managment addresses

**Comment by pehruby** [comment]
Yes, that would be nice. I just wanted to open a new issue regarding this.
Maybe even if flat is not used and the connection is established through a proxy.

**Comment by xorrkaz** [comment]
This is controlled by CML itself now.
