### ISSUE TITLE
virl ls can only see the simulation it creates but not all other simulation

### ISSUE THREAD

**Issue by christung16** [CiscoDevNet/virlutils#76]
**Describe the bug**
From the readme, It shows that virl ls can show all the simulation under the same account (def: guest/guest)
However, from what I observe, virl ls can only see the simulation it brings up. 

Is it expected?

**To Reproduce**
create two directories
put different topology in the directories.
enter "virl up" in directory 1
enter "virl ls" (expected to see one simulation)
enter "virl up" in directory 2
enter "virl ls" (expected to see two simulations. However, it only shows 1)

**Expected behavior**
Should "virl ls" show all simulation under "VIRL_USERNAME" ??
Or should we have a "global-status" option to see the simulation globally?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS,Win,CentOS

**Additional context**

**Comment by kecorbin** [comment]
If you want to see all of the simulations, try using `virl ls --all` in your steps to reproduce, `virl ls` will only show the sims luanched from that directory.  this is intendend behavior, and attempts to contextualize all the commands to a sim/project directory
