### ISSUE TITLE
virl up in version 0.8.9 raises 'path not found' exception

### ISSUE THREAD

**Issue by pk-patel** [CiscoDevNet/virlutils#83]
**Describe the bug**
Running `virl up -f topology.virl` produces the following error:
_Exception raised while running your command
Please open an issue and provide this info:
[WinError 3] The system cannot find the path specified: ''_

**To Reproduce**
1. Create new python virtual environment. `python -m venv venv` or `virtualenv venv`
2. Activate virtual environment. `source venv/bin/activate`
3. Install latest version of virlutils (0.8.9). `pip install virlutils`
4. Run `virl up -f topology.virl`  Ensure there's are valid `.virlrc` and `topology.virl` files in the local directory.

**Expected behavior**
Output should be: _Creating default environment from topology.virl._

**Desktop:**
 - OS: [Win10, Ubuntu16.04]
 - Python_Version:  [3.7.2, 2.7.16]
 - virlutils_Version: [0.8.9]

**Additional context**
Issue was reproduced with both Python 2 and Python 3 on each Windows 10 and Ubuntu 16.04.  No issues with virlutils version 0.8.8.

**Comment by xorrkaz** [comment]
This is believed to have been fixed in the latest version of virlutils (1.1.0).
