### ISSUE TITLE
Support for ncs 5.1.0

### ISSUE THREAD

**Issue by qsnyder** [CiscoDevNet/virlutils#85]
When running NSO 5.1.0 -- virlutils fails to work, probably due to NED naming differences between versions from installed default packages.

Possibly include a version check -- based on installed ncs version to generate different NED names.

**Comment by qsnyder** [comment]
I can try to work on this in my free time -- based on simple changes of values based on ncs --version?

**Comment by xorrkaz** [comment]
This has been added in the master branch pending the next release.  I tested this with NSO 5.4.
