### ISSUE TITLE
virl up virlfiles/2-ios-router is not working

### ISSUE THREAD

**Issue by shanmmur** [CiscoDevNet/virlutils#88]
(py3-venv) SHANMMUR-M-D1J9:NSO_U shanmmur$ virl up virlfiles/2-ios-router
Pulling from virlfiles/2-ios-router
Saved topology as topology.virl
Creating default environment from topology.virl
Exception raised while running your command
Please open an issue and provide this info:
HTTPConnectionPool(host='10.194.141.30', port=19399): Max retries exceeded with url: /openstack/rest/networks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1022844e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

**Comment by xorrkaz** [comment]
This is a problem with your CML/VIRL instance and not virlutils.  Either your services are not all running correctly, or the machine on which you're running virultils cannot reach the VIRL/CML server.
