### ISSUE TITLE
Unable to clone: git clone https://github.com/CiscoDevNet/really_awesome_demo

### ISSUE THREAD

**Issue by shanmmur** [CiscoDevNet/virlutils#89]
(py3-venv) SHANMMUR-M-D1J9:NSO_U shanmmur$ git clone https://github.com/CiscoDevNet/really_awesome_demo
Cloning into 'really_awesome_demo'...
Username for 'https://github.com': shanmmur
Password for 'https://shanmmur@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/CiscoDevNet/really_awesome_demo/' not found

**Comment by xorrkaz** [comment]
This is not a valid git repository..  You need to point to a valid repo.  On top of that, this doesn't appear to have anything to do with virlutils.
