### ISSUE TITLE
'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by judenoel** [CiscoDevNet/virlutils#90]
I got this error when virl up any topology

(venv) Mac:virlutils nseung$ virl up virlfiles/2-ios-router
Creating default environment from topology.virl
Exception raised while running your command
Please open an issue and provide this info:
'NoneType' object has no attribute 'endswith'

**Comment by xorrkaz** [comment]
This is believed to be fixed in the latest version of virlutils.
