### ISSUE TITLE
Virl Up Fails on Centos 7 See Details Below.

### ISSUE THREAD

**Issue by fordjes** [CiscoDevNet/virlutils#91]
Just setup Virl PE as well as Virl Utils on my Linux host I used for dev. When I attempt to setup a simulation using Virl Utils drawing from the github/virlfiles repo for my base topology I get the below error. Does anyone have any insight into this issue and how to test and verify Virl VM reachability?

[admin@localhost Virl_Util]$ virl up -f topology.virl 
Creating default environment from topology.virl
Exception raised while running your command
Please open an issue and provide this info:
expected str, bytes or os.PathLike object, not NoneType

**Comment by tepene** [comment]
How did you install virlutils? I first ran into the same issue on my linux machine. Installing with **python setup.py install** led to the described issue. I then deleted my installation and used **pip install virlutils** instead. Now it's working. To me it looks like an issue with setup.py

**Comment by xorrkaz** [comment]
This is fixed in 1.0.1.
