### ISSUE TITLE
504 Server Error

### ISSUE THREAD

**Issue by vishalpatil86** [CiscoDevNet/virlutils#92]
Trying to run one of the topologies using comand- virl up virlfiles/2-ios-router
getting **_504 Server Error: Gateway Timeout for url: http://xx.xx.xx.xx:19399/openstack/rest/networks_** error

**Comment by xorrkaz** [comment]
This is a problem with your CML/VIRL instance and not virlutils.  Either your services are not all running correctly, or the machine on which you're running virultils cannot reach the VIRL/CML server.
