### ISSUE TITLE
Sim name already running

### ISSUE THREAD

**Issue by xantihermo** [CiscoDevNet/virlutils#96]
Hi,

I get the issue that the virl up commands says the sim is already running but it's not.
I reïnstalled the virl server and also checked his database and the entry is not there.
I traced the error back to this py script:
/36env/lib/python3.6/site-packages/virl/cli/up/commands.py
I didn't got this error from the first time running, it took maybe 10 times.
Same error on MAC and Linux devices.

(36env) xanti@pheip:~$ virl ls
Running Simulations
╒══════════════╤══════════╤════════════╤═══════════╕
│ Simulation   │ Status   │ Launched   │ Expires   │
╞══════════════╪══════════╪════════════╪═══════════╡
╘══════════════╧══════════╧════════════╧═══════════╛
(36env) xanti@pheip:~$ virl up -f Virl-Topologies/2-ios-router/topology.virl
Sim xanti_default_0j3RUC already running
(36env) xanti@pheip:~$ virl down
Exception raised while running your command
Please open an issue and provide this info:
404 Client Error: Simulation "xanti_default_0j3RUC" not found. for url: http://172.25.100.25:19399/simengine/rest/stop/xanti_default_0j3RUC
(36env) xanti@pheip:~$ virl --version
Usage: virl [OPTIONS] COMMAND [ARGS]...
Try "virl --help" for help.

Error: no such option: --version
(36env) xanti@pheip:~$ virl version
virlutils Version: 0.8.8
VIRL Core Version: 0.10.37.33

Regards,

Xanti

**Comment by hpreston** [comment]
This is often caused by a previously running simulation that was stopped from the VIRL GUI and not virlutils.  Look for a hidden `.virl` directory.. if it's there just delete it and try again.

**Comment by xantihermo** [comment]
Hank,

Thanks for the follow up.
It's correct to state it was due to spinning it up with virl-utils and tearing it down in the gui.
When deleted from the .virl file it works again.

Regards.
