### ISSUE TITLE
Problem if not all configuration options are provided in .virlrc

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/virlutils#99]
**Describe the bug**
Testing with a .virlrc file and getting error `expected str, bytes or os.PathLike object, not NoneType` on all commands with only this added to the file. 

```
VIRL_HOST=*********
VIRL_USERNAME=*********
VIRL_PASSWORD=*********
```

Testing with `virl ls --all`. 

Tracked back the problem to https://github.com/CiscoDevNet/virlutils/blob/cml2-dev/virl/api/credentials.py#L70 

All the properties included in this list

```
    configurable_props = [
        "VIRL_TELNET_COMMAND",
        "VIRL_CONSOLE_COMMAND",
        "VIRL_SSH_COMMAND",
        "VIRL_SSH_USERNAME",
        "CML_CONSOLE_COMMAND",
        "CML2_PLUS",
    ]
```

Are assumed to be present.. in the configuration file.  We should assume some reasonable defaults here.

**Comment by xorrkaz** [comment]
This is fixed now.  Essentially, because of the cert failure, your CML 2+ server was being treated like a VIRL 1.x server.
